name: Test

on:
  push:
    branches: [root]
  pull_request:
    branches: [root]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Validate
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
          Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Lint
        run: |
          $excludedRules = @(
              'PSAvoidUsingConvertToSecureStringWithPlainText'
          )
          $results = Invoke-ScriptAnalyzer -ExcludeRule $excludedRules -Path .\rcgmsa.ps1 -Severity Error

          if ($results) {
              $results | Format-Table
              Write-Error 'PSScriptAnalyzer found issues. Please fix them.'
          } else {
              Write-Host 'PSScriptAnalyzer passed.'
          }

      - name: Test
        run: |
          $config = New-PesterConfiguration
          $config.Output.Verbosity = 'Detailed'
          $config.Run.Exit = $true
          $config.Run.Path = .\tests\rcgmsa.Tests.ps1

          $result = Invoke-Pester -Configuration $config

          if ($result.FailedCount -gt 0) {
              exit 1
          }
